# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

[GLOBAL]
pants_version = "2.15.0"
backend_packages = [
  "pants.backend.build_files.fmt.black",  
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
]

[anonymous-telemetry]
enabled = false

[source]
# The Python source root is the repo root. See https://www.pantsbuild.org/docs/source-roots.
root_patterns = [
  "/src/python",
  # "/src/go",
  # "/src/docker",
]

[python]
# The default interpreter constraints for code in this repo. Individual targets can override
#  this with the `interpreter_constraints` field. See
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility.

# Modify this if you don't have Python 3.9 on your machine.
# This can be a range, such as [">=3.8,<3.11"], but it's usually recommended to restrict
# to a single minor version.
interpreter_constraints = ["==3.9.*"]

# Enable the "resolves" mechanism, which turns on lockfiles for user code. See
# https://www.pantsbuild.org/docs/python-third-party-dependencies. This also adds the
# `generate-lockfiles` goal for Pants to generate the lockfile for you.
enable_resolves = true

resolves = { python-default = "3rdparty/python/python-default.lock"}

[python-bootstrap]
# We search for interpreters both on the $PATH and in the `$(pyenv root)/versions` folder.
#  If you're using macOS, you may want to leave off the <PATH> entry to avoid using the
#  problematic system Pythons. See
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path.
search_path = ["<PATH>", "<PYENV>"]

[test]
output = "all"

[pytest]
# verbose option
args = ["-v"]

# Add plugins
# Read more on https://www.pantsbuild.org/docs/python-test-goal#pytest-version-and-plugins
extra_requirements = ["pytest-asyncio"]

# Custom lockfile to use plugin from extra_requirements field
# Read more on https://www.pantsbuild.org/docs/python-third-party-dependencies#tool-lockfiles
lockfile = "3rdparty/python/pytest.lock"

[flake8]
args = [
  "--ignore", "E203,W503,F405",
  "--max-line-length", "88",
  "--exclude", "__init__.py,.mypy_cache,.pytest_cache",
]

[isort]
args = [
  "--profile", "black",
]