version: '3'

# Quickstart: 
# 1. Copy .env.dev.example as .env.dev in deploy/env directory
# 2. docker compose -f deploy/compose/docker-compose.dev.yml --env-file
# deploy/env/.env.dev config
services:
  shortener_db:
    image: postgres:13.7
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-postgre}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgre}
    ports:
      - "5432:5432"
    volumes:
      - shortener_db_data:/var/lib/postgresql/data

volumes:
  shortener_db_data:
