python_source(
    name="fastapi_app.py",
    source="fastapi_app.py",
)

python_source(
    name="migrate.py",
    source="migrate.py",
    dependencies=["src/python/shortener/migration/alembic/env.py"],
)
